pipeline{
    agent any
    stages{
        stage("Step 1"){
            steps{
                echo "this is stage 1"
            }
        }
        stage("Step 2"){
            steps{
                echo "this is stage 2"
            }
        }
        stage("Step 3"){
            steps{
                echo "this is stage 3"
            }
        }
        stage("Step 4"){
            steps{
                echo "this is stage 4"
            }
        }
        stage("Step 5"){
            steps{
                echo "this is stage 5"
            }
        }
    }
}
